### ISSUE TITLE
Check WP.org plugin/theme info

### ISSUE THREAD

**Issue by schlessera** [WordPress/servehappy#29]

**Comment by felixarntz** [comment]
We would need to clarify what exactly to check for:

* There is no "Tested up to PHP version" field. Even if there was, we would need to explain that a wrong number there might only indicate that the developer has not updated it reasonably. And that's actually why I agree such a field should not exist. It's certainly great in theory, but only confusing in practice.
* The plugin being regularly updated is a good indicator that developers are responsible about it. More particularly, if a plugin has not been updated in a long time, it's much more likely to cause compatibility issues.

**Comment by Mte90** [comment]
And probably do that check as cascade before the check for the header and next for the last update.

**Comment by felixarntz** [comment]
Summary from https://make.wordpress.org/core/2017/10/20/php-meeting-recap-october-16th/:
> It was decided that this point should not be included. There is no plugin information on the maximum supported PHP version, and even if there was, the majority of plugin authors would not update it accordingly over time (the same issue that is currently happening with the “Tested up to” field for the WordPress version). Furthermore, most developers whose plugins have issues on a more modern PHP version likely do not know about it or are not maintaining the plugin any longer.
