### ISSUE TITLE
Test locally/on staging

### ISSUE THREAD

**Issue by schlessera** [WordPress/servehappy#30]

**Comment by felixarntz** [comment]
Pasting @nerrad's original comment from #24 into here:

**Test things out on a staging/development site first.**

Pros:
- allows site owners to keep production site live while verifying things will work on the next php version.
- allows site owners to verify any plugin/theme/custom-code updates needed for php compatibility work as expected.

Cons:
- Not easy technically to setup a staging site separately from production (while authentically  mimicking production).

Other:
- This suggestion would be something that could be linked to some list of hosts that support staging sites (which could make it easier for folks).  However, its possible not every host offering staging for sites supports staging on different PHP versions.

**Comment by Mte90** [comment]
Maybe that can be a best practice suggestions but not everyone can have the knowledge to understand the difference between a staging/production site.

**Comment by nerrad** [comment]
While I agree that this is likely overly technical for the intended audience (site owners) I do think it's of benefit to at least introduce it as an option (with perhaps some links to other resources diving into how to implement a staging site).  Also,  hosts resource (the resource containing links to instructions on updating) on wp.org could maybe be tagged/categorized if they  include some form of staging for customers and we can link to that archive view for site owners to check if their host supports staging.

I do think that it's good to promote best practices of having some sort of staging site for upgrades like this.

**Comment by felixarntz** [comment]
Summary from https://make.wordpress.org/core/2017/10/20/php-meeting-recap-october-16th/:
> This point should be ditched, as it is much too advanced. A local environment is definitely not something trivial to set up for a non-technical person. For staging it depends on the site owner’s hosting provider again, but even on hosts that offer 1-Click-Staging, it can be a complex task – especially since several hosts do not allow changing PHP versions differently between the environments of a single site.
